#!/bin/sh
program="$(dmenu-wl_path | dmenu-wl "$@")"

if [ "$(echo $program | head -n1 | awk '{print $1;}')" = "maths" ]; then
	echo $program | sed 's/(/\\(/g' | sed 's/)/\\)/g' | /bin/bash &
else
	echo $program | eval "$SHELL &"
fi
